### ISSUE TITLE
Error:PyTorch built without distributed support

### ISSUE THREAD

**Issue by ppnan1** [narumiruna/pytorch-distributed-example#4]
Hi,I would like to build my distributed pytorch,
but this error was reported when I entered the code
"python main.py --init-method tcp://127.0.0.1:23456 --rank 0 --world-size 3"
and I don't konw what to do 
Any suggestion or reference project would be appreciated
thanks

**Comment by narumiruna** [comment]
Hi, What's the OS you used to execute this python code? 
In my experience, Windows PyTorch does not support distributed.
