### ISSUE TITLE
Sampling data

### ISSUE THREAD

**Issue by hgjung3** [narumiruna/pytorch-distributed-example#5]
It seems that your code does not sample the dataset for each process to have different training images during an iteration. For example, if we have 
```
Training images A, B, C, D 
2 processes
Batch size 2
```
then, during an iteration, we may want that a process has A,B and another has C,D.
To achieve this, it seems that an official example provided by PyTorch uses [DistributedSampler](https://github.com/pytorch/examples/blob/6fd43cd04f4677be005167157c848f0fefe131af/imagenet/main.py#L151).

Am I missing something?
Thanks

**Comment by narumiruna** [comment]
Thank you for your comment. I made this commit 3cfcb96b58a6199de7e6371adc3b447b6200d2e6 by refering the example.
