### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by overfitover** [narumiruna/pytorch-distributed-example#6]
Now I stop here.
Namespace(backend='tcp', init_method='tcp://192.168.1.20:12345', rank=0, steps=20, world_size=3)
What should I do?

**Comment by overfitover** [comment]
Could you give me some suggestions?

**Comment by narumiruna** [comment]
Did you execute the other two commands?
`$ python main.py --init-method tcp://192.168.1.20:12345 --rank 1 --world-size 3`
`$ python main.py --init-method tcp://192.168.1.20:12345 --rank 2 --world-size 3`

**Comment by overfitover** [comment]
Thank you very much! These are the same result.They seem to be independent.What is the connection between them?

**Comment by jeeyung** [comment]
same issue here, but the solution doesn't help for me

**Comment by overfitover** [comment]
if your world_size=3,you must execute three commands.just like
$ python main.py --init-method tcp://192.168.1.20:12345 --rank 0 --world-size 3
$ python main.py --init-method tcp://192.168.1.20:12345 --rank 1 --world-size 3
$ python main.py --init-method tcp://192.168.1.20:12345 --rank 2 --world-size 3

rank 0 must execute first.
@jeeyung
