### ISSUE TITLE
RuntimeError : Address already in use at /opt/conda/conda-bld/pytorch_1535491974311/work/torch/lib/THD/process_g roup/General.cpp:17

### ISSUE THREAD

**Issue by jeeyung** [narumiruna/pytorch-distributed-example#7]
When I try to run 'main.py', the error occur.
I don't know the reason.

**Comment by Mrmoore98** [comment]
I got same problem when I run this code in multi machine, but it works in single machine.

**Comment by narumiruna** [comment]
Please try this branch https://github.com/narumiruna/pytorch-distributed-example/tree/migrate-to-pytorch-1-0-1/mnist, and set the env variable:
`GLOO_SOCKET_IFNAME, for example export GLOO_SOCKET_IFNAME=eth0`
https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use

**Comment by Mrmoore98** [comment]
Thx for reply，but I don't know where to set environment variable is this means os.environ[' GLOO_SOCKET_IFNAME']=eth0 or set in linux?   I am new to linux and distributed computing

**Comment by narumiruna** [comment]
> Thx for reply，but I don't know where to set environment variable is this means os.environ[' GLOO_SOCKET_IFNAME']=eth0 or set in linux? I am new to linux and distributed computing

Use `ifconfig` to find your internet interface

If your internet interface is 'eth0', you can use this command to set the environment variable
`$ export GLOO_SOCKET_IFNAME=eth0`
or 
`os.environ["GLOO_SOCKET_IFNAME"]="eth0"`
in python.

**Comment by Mrmoore98** [comment]
I try your method， however it not work and shows same problem.
![problemsofParallel](https://user-images.githubusercontent.com/23526256/54581444-cb923180-4a47-11e9-8d61-88624c981bff.png)

**Comment by narumiruna** [comment]
Could you give me more information about your environment, e.q. python version, pytorch version (how you installed it? conda, pip, ...), OS version, CUDA/cuDNN version, or more. It can help me to reproduce the problem. Thank you.

**Comment by Mrmoore98** [comment]
The above problem I use Ubuntu 16.04 LTS as rank 0 and another is  ubuntu  18.04 LTS.  Both of environment installed  by pip and  set device with cpu.   
torch==1.0
torchvision==0.2.1(rank0) and 0.2.2(rank1)

Dose the linux version affect the program's performance? i try your program in two identical computer(with same cpu, enviroment and system ubuntu  18.04 LTS ) rank 1 is work and download mnist dataset and rank 0 did nothing.

**Comment by narumiruna** [comment]
> The above problem I use Ubuntu 16.04 LTS as rank 0 and another is ubuntu 18.04 LTS. Both of environment installed by pip and set device with cpu.
> torch==1.0
> torchvision==0.2.1(rank0) and 0.2.2(rank1)
> 
> Dose the linux version affect the program's performance? i try your program in two identical computer(with same cpu, enviroment and system ubuntu 18.04 LTS ) rank 1 is work and download mnist dataset and rank 0 did nothing.

Try pytorch v1.0.1?

**Comment by Mrmoore98** [comment]
ubuntu 16.04 is 0.4.1 and ubuntu 18.04 are 1.0.1

**Comment by Mrmoore98** [comment]
I fix it, seems to be the problem of torch version and systems' version, Thank you for your help!
